### ISSUE TITLE
Can I generate ".qzv" on a headless system?

### ISSUE THREAD

**Issue by izaakm** [qiime2/qiime2#312]
I'm trying to generate these ".qzv" visualization "artifacts" on a headless system. I expected that the file would be created, regardless of the fact that the system is running headless. This was on "moving pictures" tutorial.

    $ qiime demux summarize \
      --i-data demux.qza \
      --o-visualization demux.qzv

    Plugin error from demux:

        Invalid DISPLAY variable

    Debug info has been saved to /tmp/qiime2-q2cli-err-o_fl9irr.log.

    $ cat /tmp/qiime2-q2cli-err-o_fl9irr.log
    Traceback (most recent call last):
    File "/home/user/anaconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/q2cli/commands.py", line 222, in __call__
      results = action(**arguments)
    File "<decorator-gen-263>", line 2, in summarize
    File "/home/user/anaconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/qiime2/sdk/action.py", line 201, in callable_wrapper
      output_types, provenance)
    File "/home/user/anaconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/qiime2/sdk/action.py", line 392, in _callable_executor_
      ret_val = callable(output_dir=temp_dir, **view_args)
    File "/home/user/anaconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/q2_demux/_summarize/_visualizer.py", line 162, in summarize
      ax = sns.distplot(result, kde=False)
    File "/home/user/anaconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/seaborn/distributions.py", line 161, in distplot
      ax = plt.gca()
    File "/home/user/anaconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/matplotlib/pyplot.py", line 950, in gca
      return gcf().gca(**kwargs)
    File "/home/user/anaconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/matplotlib/pyplot.py", line 586, in gcf
      return figure()
    File "/home/user/anaconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/matplotlib/pyplot.py", line 535, in figure
      **kwargs)
    File "/home/user/anaconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 44, in new_figure_manager
      return new_figure_manager_given_figure(num, thisFig)
    File "/home/user/anaconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 51, in new_figure_manager_given_figure
      canvas = FigureCanvasQTAgg(figure)
    File "/home/user/anaconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 242, in __init__
      super(FigureCanvasQTAgg, self).__init__(figure=figure)
    File "/home/user/anaconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 66, in __init__
      super(FigureCanvasQTAggBase, self).__init__(figure=figure)
    File "/home/user/anaconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 236, in __init__
      _create_qApp()
    File "/home/user/anaconda3/envs/qiime2-2017.7/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 144, in _create_qApp
      raise RuntimeError('Invalid DISPLAY variable')
    RuntimeError: Invalid DISPLAY variable

    $ tree
    .
    ├── demux.qza
    ├── emp-single-end-sequences
    │   ├── barcodes.fastq.gz
    │   └── sequences.fastq.gz
    ├── emp-single-end-sequences.qza
    └── sample-metadata.tsv

**Comment by thermokarst** [comment]
Hi @izaakm, can you please post this on the [QIIME 2 Forum](https://forum.qiime2.org) --- that is where we provide user support for QIIME 2. Thanks!
