### ISSUE TITLE
Metadata with blank rows difficult to diagnose

### ISSUE THREAD

**Issue by thermokarst** [qiime2/qiime2#336]
Metadata with empty rows:
<img width="252" alt="screen shot 2017-09-21 at 6 53 18 pm" src="https://user-images.githubusercontent.com/274668/30728052-442d0e84-9f0a-11e7-9c6c-63c3fe4949b9.png">

Validation exception, while technically true, doesn't really help solve the problem.
```bash
Traceback (most recent call last):
  File "/Users/matthew/miniconda3/envs/q2dev-2017.9/bin/qiime", line 11, in <module>
    load_entry_point('q2cli', 'console_scripts', 'qiime')()
  File "/Users/matthew/miniconda3/envs/q2dev-2017.9/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/matthew/miniconda3/envs/q2dev-2017.9/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/matthew/miniconda3/envs/q2dev-2017.9/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/matthew/miniconda3/envs/q2dev-2017.9/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/matthew/miniconda3/envs/q2dev-2017.9/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/matthew/miniconda3/envs/q2dev-2017.9/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/matthew/caporaso/qiime2/q2cli/q2cli/commands.py", line 189, in __call__
    arguments, missing_in, verbose, quiet = self.handle_in_params(kwargs)
  File "/Users/matthew/caporaso/qiime2/q2cli/q2cli/commands.py", line 281, in handle_in_params
    kwargs, fallback=cmd_fallback
  File "/Users/matthew/caporaso/qiime2/q2cli/q2cli/handlers.py", line 378, in get_value
    metadata.append(qiime2.Metadata.load(path))
  File "/Users/matthew/miniconda3/envs/q2dev-2017.9/lib/python3.5/site-packages/qiime2/metadata.py", line 120, in load
    return cls(df)
  File "/Users/matthew/miniconda3/envs/q2dev-2017.9/lib/python3.5/site-packages/qiime2/metadata.py", line 55, in __init__
    _validate_pandas_index(dataframe.index, 'index')
  File "/Users/matthew/miniconda3/envs/q2dev-2017.9/lib/python3.5/site-packages/qiime2/metadata.py", line 29, in _validate_pandas_index
    raise ValueError(invalid_metadata_template % msg)
ValueError: Non-string Metadata index values detected. There may be more errors present in this metadata. Currently only QIIME 1 sample/feature metadata mapping files are officially supported. Sample metadata files can be validated using Keemei: http://keemei.qiime.org.
```

It would be nice to check specifically for blank rows and report back on that to the user.

This recently came up on [the forum](https://forum.qiime2.org/t/error-in-command-for-generating-pcoa-plot/1251?u=thermokarst).

**Comment by antgonza** [comment]
Not sure what the best solution for this is, are there any suggestions? I perhaps could help with this ...

Just FYI, in Qiita, we do the load in 2 steps, the first step checks for [non UTF-8 chars](https://github.com/biocore/qiita/blob/release-candidate/qiita_db/metadata_template/util.py#L108) and then we use [this](https://github.com/biocore/qiita/blob/release-candidate/qiita_db/metadata_template/util.py#L170) pandas command to open/parse the file. BTW we think is fine to do it 2 step cause this only happens on queues in Qiita so the process might take a few seconds more but the solution seems worth it at this time.

**Comment by jairideout** [comment]
Thanks for offering to work on this @antgonza! I ended up pushing this in for 2017.9, but we would love to have your help on other issues for the upcoming 2017.10 release.

I have an open PR if you're curious how I solved the problem: https://github.com/qiime2/qiime2/pull/341 (use `dropna()` to drop empty rows before setting the index).

**Comment by antgonza** [comment]
K, will review.
