### ISSUE TITLE
Timezone error while running qiime2 in a singularity container

### ISSUE THREAD

**Issue by chetana93** [qiime2/qiime2#493]
Hello everyone,

I'm trying to run qiime2 version 2019.7 in a singularity container with all the dependencies installed in it. But I'm getting this error when I try to run the qiime2 pipeline, please find it below. Could someone please help me fix it. Thanks in advance.

"Timezone offset does not match system offset: 0 != -25200. Please, check your config files." 

Traceback (most recent call last):

  File "/opt/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/q2cli/commands.py", line 327, in __call__

    results = action(**arguments)

  File "</opt/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/decorator.py:decorator-gen-232>", line 2, in tabulate

  File "/opt/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/sdk/action.py", line 240, in bound_callable

    output_types, provenance)

  File "/opt/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/sdk/action.py", line 452, in _callable_executor_

    provenance)

  File "/opt/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/sdk/result.py", line 342, in _from_data_dir

    provenance_capture=provenance_capture)

  File "/opt/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/core/archive/archiver.py", line 316, in from_data

    Format.write(rec, type, format, data_initializer, provenance_capture)

  File "/opt/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/core/archive/format/v5.py", line 21, in write

    provenance_capture)

  File "/opt/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/core/archive/format/v1.py", line 26, in write

    prov_dir, [root / cls.METADATA_FILE, archive_record.version_fp])

  File "/opt/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/core/archive/provenance.py", line 312, in finalize

    self.write_action_yaml()

  File "/opt/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/core/archive/provenance.py", line 289, in write_action_yaml

    fh.write(yaml.dump({'execution': self.make_execution_section()},

  File "/opt/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/core/archive/provenance.py", line 255, in make_execution_section

    runtime['start'] = start = self._ts_to_date(self.start)

  File "/opt/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/core/archive/provenance.py", line 249, in _ts_to_date

    return datetime.fromtimestamp(ts, tzlocal.get_localzone())

  File "/opt/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/tzlocal/unix.py", line 165, in get_localzone

    _cache_tz = _get_localzone()

  File "/opt/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/tzlocal/unix.py", line 90, in _get_localzone

    utils.assert_tz_offset(tz)

  File "/opt/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/tzlocal/utils.py", line 38, in assert_tz_offset

    raise ValueError(msg)

ValueError: Timezone offset does not match system offset: 0 != -25200. Please, check your config files.

**Comment by thermokarst** [comment]
Hi @chetana93! I suspect this is a cross-post related to this forum post: https://forum.qiime2.org/t/error-while-running-qiime2-valueerror-timezone-offset-does-not-match-system-offset-0-25200-please-check-your-config-files/11418

Can you please post the information you shared here back over on the original post? We will conduct our support on the forum for you - thank you!

**Comment by chetana93** [comment]
Sure. Thanks!

**Comment by d4straub** [comment]
Hi all,

I have a related problem, see https://github.com/nf-core/ampliseq/issues/114. Essentially, I have a container executed with singularity operated by nextflow. When I upgraded from 2018.6 to 2019.10 the timezone error appeared and makes the pipeline unusable.

Also exporting the timezone (`export TZ='Europe/Berlin'`) and transfering it to the container using the singularity option `envWhiteList='TZ'` did not help. 

Any advice?

**Comment by thermokarst** [comment]
Hi @d4straub - we don't provide singularity containers - please chat with the person who built the one you are using, and let them know that the environment isn't configured correctly - you need to [configure the timezone environment variables](https://forum.qiime2.org/t/error-while-running-qiime2-valueerror-timezone-offset-does-not-match-system-offset-0-25200-please-check-your-config-files/11418).

**Comment by thermokarst** [comment]
Hi @d4straub, just wanted to let you know I opened a new issue over at https://github.com/qiime2/qiime2/issues/510 for discussing potential changes related to tzlocal. Thanks!
