### ISSUE TITLE
DADA2 in QIIME2 - Return Code 1

### ISSUE THREAD

**Issue by KCalapa** [qiime2/qiime2#517]
Hello,
I am pretty new to using QIIME2.  I have already imported my data via the manifests version, and I am currently trying to denoise my data using DADA2.  I keep getting Return Code one, and I did to a qiime tools validate on the file and everything seems to be ok.  Not sure how to proceed.  My error is pasted below.  Thanks!

qiime dada2 denoise-paired \
> --i-demultiplexed-seqs paired-end-demux.qza \
> --p-trim-left-f 15 \
> --p-trim-left-r 15 \
> --p-trunc-len-f 225 \
> --p-trunc-len-r 205 \
> --p-n-threads 0 \
> --o-table table.qza \
> --o-representative-sequences rep_seqs.qza \
> --o-denoising-stats denoising_stats.qza \
> --verbose
Running external command line application(s). This may print messages to stdout and/or stderr.
The command(s) being run are below. These commands cannot be manually re-run as they will depend on temporary files that no longer exist.

Command: run_dada_paired.R /tmp/tmp450ej6il/forward /tmp/tmp450ej6il/reverse /tmp/tmp450ej6il/output.tsv.biom /tmp/tmp450ej6il/track.tsv /tmp/tmp450ej6il/filt_f /tmp/tmp450ej6il/filt_r 225 205 15 15 2.0 2.0 2 consensus 1.0 0 1000000

R version 3.5.1 (2018-07-02) 
Loading required package: Rcpp
DADA2: 1.10.0 / Rcpp: 1.0.2 / RcppParallel: 4.4.4 
1) Filtering Error in names(answer) <- names1 : attempt to set an attribute on NULL
Execution halted
Traceback (most recent call last):
  File "/home/qiime2/miniconda/envs/qiime2-2019.10/lib/python3.6/site-packages/q2_dada2/_denoise.py", line 257, in denoise_paired
    run_commands([cmd])
  File "/home/qiime2/miniconda/envs/qiime2-2019.10/lib/python3.6/site-packages/q2_dada2/_denoise.py", line 36, in run_commands
    subprocess.run(cmd, check=True)
  File "/home/qiime2/miniconda/envs/qiime2-2019.10/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['run_dada_paired.R', '/tmp/tmp450ej6il/forward', '/tmp/tmp450ej6il/reverse', '/tmp/tmp450ej6il/output.tsv.biom', '/tmp/tmp450ej6il/track.tsv', '/tmp/tmp450ej6il/filt_f', '/tmp/tmp450ej6il/filt_r', '225', '205', '15', '15', '2.0', '2.0', '2', 'consensus', '1.0', '0', '1000000']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qiime2/miniconda/envs/qiime2-2019.10/lib/python3.6/site-packages/q2cli/commands.py", line 328, in __call__
    results = action(**arguments)
  File "</home/qiime2/miniconda/envs/qiime2-2019.10/lib/python3.6/site-packages/decorator.py:decorator-gen-459>", line 2, in denoise_paired
  File "/home/qiime2/miniconda/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/sdk/action.py", line 240, in bound_callable
    output_types, provenance)
  File "/home/qiime2/miniconda/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/sdk/action.py", line 383, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/home/qiime2/miniconda/envs/qiime2-2019.10/lib/python3.6/site-packages/q2_dada2/_denoise.py", line 272, in denoise_paired
    " and stderr to learn more." % e.returncode)
Exception: An error was encountered while running DADA2 in R (return code 1), please inspect stdout and stderr to learn more.

Plugin error from dada2:

  An error was encountered while running DADA2 in R (return code 1), please inspect stdout and stderr to learn more.

See above for debug info.

**Comment by thermokarst** [comment]
Hi @KCalapa! Please post this to the QIIME 2 Forum (https://forum.qiime2.org), that is where we provide this kind of user support. Thanks!
