### ISSUE TITLE
Conflicting packages in a conda environment cause confusing errors

### ISSUE THREAD

**Issue by fedarko** [qiime2/qiime2#532]
**Bug Description**
Having packages installed that conflict with other installed plugins' requirements seems to cause most actions in QIIME 2 to fail. While failure isn't necessarily unexpected behavior in this situation, the error messages seem pretty confusing -- it took me a decent amount of struggling to figure out what the problem was, and I expect other users will also fall into this problem eventually.

**Steps to reproduce the behavior**
1. In a QIIME 2 conda environment (I've tested this on QIIME 2 2019.10), `pip`-install a version of a package that deliberately conflicts with what's specified in a Q2 plugin's `setup.py`. For example, installing `pandas==1.0.3` in a environment where [Qurro](https://library.qiime2.org/plugins/qurro/22/) is installed (since Qurro requires that a pandas version that satisfies `"pandas >= 0.24.0, <1"` is installed).
2. Try to run -- what seems to me -- basically any Q2 plugin within the now-"unsatisfiable" QIIME 2 environment. Here I'll use `qiime taxa barplot` as an example, but I've observed this with other plugins.

```bash
qiime taxa barplot \
    --i-table table.qza \
    --i-taxonomy taxonomy.qza \
    --m-metadata-file metadata.txt \
    --o-visualization tbp.qzv
```

This triggers the following error:

```
Usage: qiime taxa barplot [OPTIONS]

  This visualizer produces an interactive barplot visualization of
  taxonomies. Interactive features include multi-level sorting, plot
  recoloring, sample relabeling, and SVG figure export.

Inputs:
  --i-table ARTIFACT FeatureTable[Frequency]
                         Feature table to visualize at various taxonomic
                         levels.                                    [required]
  --i-taxonomy ARTIFACT FeatureData[Taxonomy]
                         Taxonomic annotations for features in the provided
                         feature table. All features in the feature table must
                         have a corresponding taxonomic annotation. Taxonomic
                         annotations that are not present in the feature table
                         will be ignored.                           [required]
Parameters:
  --m-metadata-file METADATA...
    (multiple            The sample metadata.
     arguments will be   
     merged)                                                        [required]
Outputs:
  --o-visualization VISUALIZATION
                                                                    [required]
Miscellaneous:
  --output-dir PATH      Output unspecified results to a directory
  --verbose / --quiet    Display verbose output to stdout and/or stderr
                         during execution of this action. Or silence output if
                         execution is successful (silence is golden).
  --citations            Show citations and exit.
  --help                 Show this message and exit.

                  There were some problems with the command:                  
 (1/2) Invalid value for "--i-table": 'table.qza' is not a QIIME 2 Artifact
  (.qza)
 (2/2) Invalid value for "--i-taxonomy": 'taxonomy.qza' is not a QIIME 2
  Artifact (.qza)
```

Normally I'd expect this to be due to these QZAs not existing in the specified location or being invalid or something, but these QZAs really are "normal". The cause of the problem is revealed when you try to validate these QZAs:

```bash
qiime tools validate table.qza
```

gives you

```
Traceback (most recent call last):
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/q2cli/builtin/tools.py", line 409, in validate
    result = qiime2.sdk.Result.load(path)
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/sdk/result.py", line 66, in load
    archiver = archive.Archiver.load(filepath)
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/core/archive/archiver.py", line 307, in load
    return cls(path, Format(rec))
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/core/archive/format/v1.py", line 29, in __init__
    super().__init__(archive_record)
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/core/archive/format/v0.py", line 73, in __init__
    self.format = sdk.parse_format(format)
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/sdk/util.py", line 88, in parse_format
    pm = qiime2.sdk.PluginManager()
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/sdk/plugin_manager.py", line 44, in __new__
    self._init()
  File "/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages/qiime2/sdk/plugin_manager.py", line 59, in _init
    plugin = entry_point.load()
  File "/home/marcus/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in load
    self.require(*args, **kwargs)
  File "/home/marcus/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/marcus/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pandas 1.0.3 (/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages), Requirement.parse('pandas<1,>=0.24.0'))

There was a problem loading table.qza as a QIIME 2 Result:

  (pandas 1.0.3 (/home/marcus/Software/miniconda2/envs/qiime2-2019.10/lib/python3.6/site-packages), Requirement.parse('pandas<1,>=0.24.0'))

See above for debug info.
```

As the error message implies, installing a "sane" version of pandas (`pip install pandas==0.25.2`) fixes the problem, allowing both `qiime tools validate` and the `qiime taxa barplot` command to work.

**Expected behavior**
Rather than the `qiime taxa barplot` command (or other plugins) telling the user that the input QZAs are each "`not a QIIME 2 Artifact (.qza)`", a more informative error message should be returned that explains that the environment is somehow invalid (sort of like the `qiime tools validate` command gives you).

**Computation Environment**
- OS: Ubuntu 18.04.3
- QIIME 2 Release 2019.10
- Using the `fish` terminal, if that helps

**Comments**
1. I'm guessing that when the QIIME 2 internals try to load a QZA, some sort of environment "satisfiability" check is performed -- either directly or indirectly -- and this check failing is taken to mean that the QZAs are invalid. However, in this case, the QZAs _are_ valid: so the reported error message is misleading to users.

Thanks!

**Comment by andrewsanchez** [comment]
I agree the errors that can show up due to conflicting dependencies are not ideal.  I'm not sure if we do any checks to verify the environment after conda does its thing.  I wonder if we can improve this situation by making the cache aware of the [expected requirements](https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-py36-linux-conda.yml) and issuing a warning if the user's current qiiime 2 deployment requirements conflict with those.  I'd be happy to look into a solution after getting feedback from @thermokarst and/or @ebolyen.

Thanks for your report, @fedarko!

**Comment by thermokarst** [comment]
Just a quick note - I am going to move this issue over to the q2cli tracker, since it seems to be specific to that interface - will follow up later! Thanks @fedarko!
