### ISSUE TITLE
ValueError: unsupported format character 'T' (0x54) at index 3312 when creating environment from environment file

### ISSUE THREAD

**Issue by jolespin** [qiime2/qiime2#672]
**Bug Description**
I'm getting a `ValueError: unsupported format character 'T' (0x54) at index 3312` when creating environment from environment file.  In particular, this version: `qiime2-2022.11-py38-linux-conda.yml`

**Steps to reproduce the behavior**
`conda env create -n test-qiime2_env -f qiime2-2022.11-py38-linux-conda.yml &>  qiime2-2022.11-py38-linux-conda.yml.log`

**Expected behavior**
To produce a working QIIME2 environment. 

**Screenshots**
No but I provided the log below. 

**Computation Environment**
- OS: Linux 4.18.0-348.23.1.el8_5.x86_64
- QIIME 2 Release 2022.11

Here's the log: 

```
(base) cat qiime2-2022.11-py38-linux-conda.yml.log
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 22.11.1

Please update conda by running

    $ conda update -n base -c defaults conda


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
ERROR conda.core.link:_execute(733): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.9-r42hdfd78af_0'.
Rolling back transaction: ...working... done
class: LinkError
message:
post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.9-r42hdfd78af_0
location of failed script: /expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: /expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/share/genomeinfodbdata-1.2.9/"GenomeInfoDbData_1.2.9.tar.gz": OK

stderr: QIIME is caching your current deployment for improved performance. This may take a few moments and should only happen once per deployment.
OpenBLAS blas_thread_init: pthread_create failed for thread 59 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 2000 current, 2000 max
OpenBLAS blas_thread_init: pthread_create failed for thread 60 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 2000 current, 2000 max
OpenBLAS blas_thread_init: pthread_create failed for thread 61 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 2000 current, 2000 max
OpenBLAS blas_thread_init: pthread_create failed for thread 62 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 2000 current, 2000 max
OpenBLAS blas_thread_init: pthread_create failed for thread 63 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 2000 current, 2000 max

Aborted!
/expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/bin/tab-qiime: line 54: 112446 Killed                  qiime > /dev/null
++ dirname -- /expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/bin/installBiocDataPackage.sh
+ SCRIPT_DIR=/expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/bin/../share/bioconductor-data-packages
+ json=/expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/bin/../share/bioconductor-data-packages/dataURLs.json
++ yq '."genomeinfodbdata-1.2.9".fn' /expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/bin/../share/bioconductor-data-packages/dataURLs.json
+ FN='"GenomeInfoDbData_1.2.9.tar.gz"'
+ IFS=
+ read -r value
++ yq '."genomeinfodbdata-1.2.9".urls[]' /expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/bin/../share/bioconductor-data-packages/dataURLs.json
+ URLS+=($value)
+ IFS=
+ read -r value
+ URLS+=($value)
+ IFS=
+ read -r value
+ URLS+=($value)
+ IFS=
+ read -r value
++ yq '."genomeinfodbdata-1.2.9".md5' /expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/bin/../share/bioconductor-data-packages/dataURLs.json
+ MD5='"7cc138cfb74665fdfa8d1c244eac4879"'
+ STAGING=/expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/share/genomeinfodbdata-1.2.9
+ mkdir -p /expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/share/genomeinfodbdata-1.2.9
+ TARBALL='/expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/share/genomeinfodbdata-1.2.9/"GenomeInfoDbData_1.2.9.tar.gz"'
+ SUCCESS=0
+ for URL in ${URLS[@]}
++ echo '"https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz"'
++ tr -d '"'
+ URL=https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz
++ echo '"7cc138cfb74665fdfa8d1c244eac4879"'
++ tr -d '"'
+ MD5=7cc138cfb74665fdfa8d1c244eac4879
+ curl -L https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.1M  100 11.1M    0     0  23.0M      0 --:--:-- --:--:-- --:--:-- 23.1M
+ [[ 0 == 0 ]]
++ uname -s
+ [[ Linux == \L\i\n\u\x ]]
+ md5sum -c
+ SUCCESS=1
+ break
+ [[ 1 != 1 ]]
+ R CMD INSTALL --library=/expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/lib/R/library '/expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/share/genomeinfodbdata-1.2.9/"GenomeInfoDbData_1.2.9.tar.gz"'
/expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/lib/R/bin/INSTALL: line 34: 1651576 Done                    echo 'tools:::.install_packages()'
     1651577 Killed                  | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --no-echo --args ${args}

return code: 137

kwargs:
{}

Traceback (most recent call last):
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1129, in __call__
    return func(*args, **kwargs)
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/site-packages/conda/notices/core.py", line 72, in wrapper
    return_value = func(*args, **kwargs)
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 156, in execute
    result[installer_type] = installer.install(prefix, pkg_specs, args, env)
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/site-packages/conda_env/installers/conda.py", line 59, in install
    unlink_link_transaction.execute()
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/site-packages/conda/core/link.py", line 284, in execute
    self._execute(tuple(concat(interleave(self.prefix_action_groups.values()))))
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/site-packages/conda/core/link.py", line 747, in _execute
    raise CondaMultiError(tuple(concatv(
conda.CondaMultiErrorclass: LinkError
message:
post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.9-r42hdfd78af_0
location of failed script: /expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: /expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/share/genomeinfodbdata-1.2.9/"GenomeInfoDbData_1.2.9.tar.gz": OK

stderr: QIIME is caching your current deployment for improved performance. This may take a few moments and should only happen once per deployment.
OpenBLAS blas_thread_init: pthread_create failed for thread 59 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 2000 current, 2000 max
OpenBLAS blas_thread_init: pthread_create failed for thread 60 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 2000 current, 2000 max
OpenBLAS blas_thread_init: pthread_create failed for thread 61 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 2000 current, 2000 max
OpenBLAS blas_thread_init: pthread_create failed for thread 62 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 2000 current, 2000 max
OpenBLAS blas_thread_init: pthread_create failed for thread 63 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 2000 current, 2000 max

Aborted!
/expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/bin/tab-qiime: line 54: 112446 Killed                  qiime > /dev/null
++ dirname -- /expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/bin/installBiocDataPackage.sh
+ SCRIPT_DIR=/expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/bin/../share/bioconductor-data-packages
+ json=/expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/bin/../share/bioconductor-data-packages/dataURLs.json
++ yq '."genomeinfodbdata-1.2.9".fn' /expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/bin/../share/bioconductor-data-packages/dataURLs.json
+ FN='"GenomeInfoDbData_1.2.9.tar.gz"'
+ IFS=
+ read -r value
++ yq '."genomeinfodbdata-1.2.9".urls[]' /expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/bin/../share/bioconductor-data-packages/dataURLs.json
+ URLS+=($value)
+ IFS=
+ read -r value
+ URLS+=($value)
+ IFS=
+ read -r value
+ URLS+=($value)
+ IFS=
+ read -r value
++ yq '."genomeinfodbdata-1.2.9".md5' /expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/bin/../share/bioconductor-data-packages/dataURLs.json
+ MD5='"7cc138cfb74665fdfa8d1c244eac4879"'
+ STAGING=/expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/share/genomeinfodbdata-1.2.9
+ mkdir -p /expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/share/genomeinfodbdata-1.2.9
+ TARBALL='/expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/share/genomeinfodbdata-1.2.9/"GenomeInfoDbData_1.2.9.tar.gz"'
+ SUCCESS=0
+ for URL in ${URLS[@]}
++ echo '"https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz"'
++ tr -d '"'
+ URL=https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz
++ echo '"7cc138cfb74665fdfa8d1c244eac4879"'
++ tr -d '"'
+ MD5=7cc138cfb74665fdfa8d1c244eac4879
+ curl -L https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.1M  100 11.1M    0     0  23.0M      0 --:--:-- --:--:-- --:--:-- 23.1M
+ [[ 0 == 0 ]]
++ uname -s
+ [[ Linux == \L\i\n\u\x ]]
+ md5sum -c
+ SUCCESS=1
+ break
+ [[ 1 != 1 ]]
+ R CMD INSTALL --library=/expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/lib/R/library '/expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/share/genomeinfodbdata-1.2.9/"GenomeInfoDbData_1.2.9.tar.gz"'
/expanse/projects/jcl110/anaconda3/envs/test-qiime2_env/lib/R/bin/INSTALL: line 34: 1651576 Done                    echo 'tools:::.install_packages()'
     1651577 Killed                  | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --no-echo --args ${args}

return code: 137

kwargs:
{}

: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/expanse/projects/jcl110/anaconda3/bin/conda-env", line 9, in <module>
    sys.exit(main())
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 91, in main
    return conda_exception_handler(do_call, args, parser)
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1429, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1132, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1161, in handle_exception
    return self.handle_application_exception(exc_val, exc_tb)
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1175, in handle_application_exception
    self._print_conda_exception(exc_val, exc_tb)
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1179, in _print_conda_exception
    print_conda_exception(exc_val, exc_tb)
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1106, in print_conda_exception
    stderrlog.error("\n%r\n", exc_val)
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/logging/__init__.py", line 1598, in handle
    if (not self.disabled) and self.filter(record):
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/logging/__init__.py", line 806, in filter
    result = f.filter(record)
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/site-packages/conda/gateways/logging.py", line 50, in filter
    record.msg = record.msg % new_args
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/site-packages/conda/__init__.py", line 107, in __repr__
    errs.append(e.__repr__())
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/site-packages/conda/__init__.py", line 64, in __repr__
    return '%s: %s' % (self.__class__.__name__, str(self))
  File "/expanse/projects/jcl110/anaconda3/lib/python3.9/site-packages/conda/__init__.py", line 68, in __str__
    return str(self.message % self._kwargs)
ValueError: unsupported format character 'T' (0x54) at index 3312
```

**Comment by lizgehret** [comment]
Hi @jolespin,

Please try [installing QIIME 2](https://docs.qiime2.org/2022.11/install/native/#install-qiime-2-within-a-conda-environment) once more, and you shouldn't run into this issue again.

Additionally, if you run into any further issues or have other questions regarding QIIME 2 functionality, please post on our [user forum](https://forum.qiime2.org/) for assistance! We primarily use Github for new feature requests and developer contributions. Thanks!

**Comment by jolespin** [comment]
Was there something that was just changed?  I'm wondering if it was because I had qiime2/r2022.2 in my condarc

**Comment by lizgehret** [comment]
@jolespin no, but this issue can happen as a stochastic error and re-installing can sometimes resolve it. There is a great forum post [here](https://forum.qiime2.org/t/errors-during-transaction-when-installing-qiime2-2019-10/12414) that goes through a handful of different reasons why this type of error can come up.

**Comment by jolespin** [comment]
Is there a way to JUST install stuff necessary for the DADA2 and phylogeny pipeline?

**Comment by lizgehret** [comment]
@jolespin there's most likely something funky going on with conda that's causing this issue to persist. We can help you de-bug this in greater detail on the user forum - if you could please post this issue there, that would be great. Thanks!

**Comment by jolespin** [comment]
I'll add this on the user forum but do you mind if we keep this open and close once it's actually resolved?

**Comment by jolespin** [comment]
I just tried installing again but it's the same issue that was here.  I added it on the QIIME2 forum, can we discuss possibilities here too since it's directly involved with errors in the installation?

**Comment by ebolyen** [comment]
No, please pay attention to @lizgehret response.
