### ISSUE TITLE
Can not run any command in Qiime2 env after installing songbird

### ISSUE THREAD

**Issue by emankhalaf** [qiime2/qiime2#705]
Hi,

I have PacBio 16S sequences and I use qiime2-2022.2, everything was good until I installed songbird, then I tried to import new sequences from another project, but it failed producing this error message: 
installing songbird made an issue to import data An unexpected error has occurred:

  No module named 'tensorflow.contrib'

## I checked tensorflow version as follows:
$pip freeze | grep tensorflow 
tensorflow==2.13.0
tensorflow-estimator==2.13.0
tensorflow-io-gcs-filesystem==0.33.0

##So, I tried to install the latest version of qiime2 to skip this issue using conda but I got the error below:

ERROR conda.core.link:_execute(730): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.9-r42hdfd78af_0'.
Rolling back transaction: done
class: LinkError
message:
post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.9-r42hdfd78af_0
location of failed script: /home/miniconda3/envs/qiime2-2023.5/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: QIIME is caching your current deployment for improved performance. This may take a few moments and should only happen once per deployment.
++ dirname -- /home/miniconda3/envs/qiime2-2023.5/bin/installBiocDataPackage.sh
+ SCRIPT_DIR=/home/miniconda3/envs/qiime2-2023.5/bin/../share/bioconductor-data-packages
+ json=/home/miniconda3/envs/qiime2-2023.5/bin/../share/bioconductor-data-packages/dataURLs.json
++ yq '."genomeinfodbdata-1.2.9".fn' /home/miniconda3/envs/qiime2-2023.5/bin/../share/bioconductor-data-packages/dataURLs.json
+ FN='"GenomeInfoDbData_1.2.9.tar.gz"'
+ IFS=
+ read -r value
++ yq '."genomeinfodbdata-1.2.9".urls[]' /home/miniconda3/envs/qiime2-2023.5/bin/../share/bioconductor-data-packages/dataURLs.json
+ URLS+=($value)
+ IFS=
+ read -r value
+ URLS+=($value)
+ IFS=
+ read -r value
+ URLS+=($value)
+ IFS=
+ read -r value
++ yq '."genomeinfodbdata-1.2.9".md5' /home/miniconda3/envs/qiime2-2023.5/bin/../share/bioconductor-data-packages/dataURLs.json
+ MD5='"7cc138cfb74665fdfa8d1c244eac4879"'
+ STAGING=/home/miniconda3/envs/qiime2-2023.5/share/genomeinfodbdata-1.2.9
+ mkdir -p /home/miniconda3/envs/qiime2-2023.5/share/genomeinfodbdata-1.2.9
+ TARBALL='/home/miniconda3/envs/qiime2-2023.5/share/genomeinfodbdata-1.2.9/"GenomeInfoDbData_1.2.9.tar.gz"'
+ SUCCESS=0
+ for URL in ${URLS[@]}
++ echo '"https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz"'
++ tr -d '"'
+ URL=https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz
++ echo '"7cc138cfb74665fdfa8d1c244eac4879"'
++ tr -d '"'
+ MD5=7cc138cfb74665fdfa8d1c244eac4879
+ curl -L https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   416  100   416    0     0   3367      0 --:--:-- --:--:-- --:--:--  3382
  0     0    0     0    0     0      0      0 --:--:--  0:02:11 --:--:--     0
curl: (7) Failed to connect to mghp.osn.xsede.org port 443 after 131408 ms: Couldn't connect to server

return code: 7

kwargs:
{}

Traceback (most recent call last):
  File "/home/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1114, in __call__
    return func(*args, **kwargs)
  File "/home/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/home/miniconda3/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 143, in execute
    result[installer_type] = installer.install(prefix, pkg_specs, args, env)
  File "/home/miniconda3/lib/python3.9/site-packages/conda_env/installers/conda.py", line 59, in install
    unlink_link_transaction.execute()
  File "/home/miniconda3/lib/python3.9/site-packages/conda/core/link.py", line 281, in execute
    self._execute(tuple(concat(interleave(self.prefix_action_groups.values()))))
  File "/home/miniconda3/lib/python3.9/site-packages/conda/core/link.py", line 744, in _execute
    raise CondaMultiError(tuple(concatv(
conda.CondaMultiErrorclass: LinkError
message:
post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.9-r42hdfd78af_0
location of failed script: /home/miniconda3/envs/qiime2-2023.5/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: QIIME is caching your current deployment for improved performance. This may take a few moments and should only happen once per deployment.
++ dirname -- /home/miniconda3/envs/qiime2-2023.5/bin/installBiocDataPackage.sh
+ SCRIPT_DIR=/home/miniconda3/envs/qiime2-2023.5/bin/../share/bioconductor-data-packages
+ json=/home/miniconda3/envs/qiime2-2023.5/bin/../share/bioconductor-data-packages/dataURLs.json
++ yq '."genomeinfodbdata-1.2.9".fn' /home/miniconda3/envs/qiime2-2023.5/bin/../share/bioconductor-data-packages/dataURLs.json
+ FN='"GenomeInfoDbData_1.2.9.tar.gz"'
+ IFS=
+ read -r value
++ yq '."genomeinfodbdata-1.2.9".urls[]' /home/miniconda3/envs/qiime2-2023.5/bin/../share/bioconductor-data-packages/dataURLs.json
+ URLS+=($value)
+ IFS=
+ read -r value
+ URLS+=($value)
+ IFS=
+ read -r value
+ URLS+=($value)
+ IFS=
+ read -r value
++ yq '."genomeinfodbdata-1.2.9".md5' /home/miniconda3/envs/qiime2-2023.5/bin/../share/bioconductor-data-packages/dataURLs.json
+ MD5='"7cc138cfb74665fdfa8d1c244eac4879"'
+ STAGING=/home/miniconda3/envs/qiime2-2023.5/share/genomeinfodbdata-1.2.9
+ mkdir -p /home/miniconda3/envs/qiime2-2023.5/share/genomeinfodbdata-1.2.9
+ TARBALL='/home/miniconda3/envs/qiime2-2023.5/share/genomeinfodbdata-1.2.9/"GenomeInfoDbData_1.2.9.tar.gz"'
+ SUCCESS=0
+ for URL in ${URLS[@]}
++ echo '"https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz"'
++ tr -d '"'
+ URL=https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz
++ echo '"7cc138cfb74665fdfa8d1c244eac4879"'
++ tr -d '"'
+ MD5=7cc138cfb74665fdfa8d1c244eac4879
+ curl -L https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   416  100   416    0     0   3367      0 --:--:-- --:--:-- --:--:--  3382
  0     0    0     0    0     0      0      0 --:--:--  0:02:11 --:--:--     0
curl: (7) Failed to connect to mghp.osn.xsede.org port 443 after 131408 ms: Couldn't connect to server

return code: 7

kwargs:
{}

: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/miniconda3/bin/conda-env", line 7, in <module>
    sys.exit(main())
  File "/home/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 91, in main
    return conda_exception_handler(do_call, args, parser)
  File "/home/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1404, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/home/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1117, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/home/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1148, in handle_exception
    return self.handle_application_exception(exc_val, exc_tb)
  File "/home/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1162, in handle_application_exception
    self._print_conda_exception(exc_val, exc_tb)
  File "/home/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1166, in _print_conda_exception
    print_conda_exception(exc_val, exc_tb)
  File "/home/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1091, in print_conda_exception
    stderrlog.error("\n%r\n", exc_val)
  File "/home/miniconda3/lib/python3.9/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/home/miniconda3/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/home/miniconda3/lib/python3.9/logging/__init__.py", line 1598, in handle
    if (not self.disabled) and self.filter(record):
  File "/home/miniconda3/lib/python3.9/logging/__init__.py", line 806, in filter
    result = f.filter(record)
  File "/home/miniconda3/lib/python3.9/site-packages/conda/gateways/logging.py", line 51, in filter
    record.msg = record.msg % new_args
  File "/home/miniconda3/lib/python3.9/site-packages/conda/__init__.py", line 101, in __repr__
    errs.append(e.__repr__())
  File "/home/miniconda3/lib/python3.9/site-packages/conda/__init__.py", line 58, in __repr__
    return '%s: %s' % (self.__class__.__name__, str(self))
  File "/home/miniconda3/lib/python3.9/site-packages/conda/__init__.py", line 62, in __str__
    return str(self.message % self._kwargs)
ValueError: unsupported format character 'T' (0x54) at index 2102

Your support is appreciated!

**Comment by emankhalaf** [comment]
@Oddant1 Done
