### ISSUE TITLE
uninformative error message when wrong type is passed for citations list

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#759]
In hindsight this is obvious, but took me a few mins to figure out. 

If accidentally providing a citation, rather than a list of citations, when registering plugins or actions, the error message is uninformative. For example

```python
plugin = Plugin(
    name="dwq2",
    version=__version__,
    website="https://cap-lab.bio/developing-with-qiime2/",
    package="q2_dwq2",
    description=description,
    short_description="Developing with QIIME 2 demo plugin.",
    # the following should be citations=[citations['DWQ2']]
    citations=citations['DWQ2']
)
```

```bash
$ qiime dwq2 --citations
Traceback (most recent call last):
  File "/Users/jgc/miniconda3/envs/dwq2/bin/qiime", line 11, in <module>
    sys.exit(qiime())
  File "/Users/jgc/miniconda3/envs/dwq2/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jgc/miniconda3/envs/dwq2/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/jgc/miniconda3/envs/dwq2/lib/python3.8/site-packages/click/core.py", line 1686, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/Users/jgc/miniconda3/envs/dwq2/lib/python3.8/site-packages/click/core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "/Users/jgc/miniconda3/envs/dwq2/lib/python3.8/site-packages/q2cli/click/command.py", line 43, in parse_args
    return super().parse_args(ctx, args)
  File "/Users/jgc/miniconda3/envs/dwq2/lib/python3.8/site-packages/click/core.py", line 1644, in parse_args
    rest = super().parse_args(ctx, args)
  File "/Users/jgc/miniconda3/envs/dwq2/lib/python3.8/site-packages/click/core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/Users/jgc/miniconda3/envs/dwq2/lib/python3.8/site-packages/click/core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/Users/jgc/miniconda3/envs/dwq2/lib/python3.8/site-packages/click/core.py", line 2362, in process_value
    value = self.callback(ctx, self, value)
  File "/Users/jgc/miniconda3/envs/dwq2/lib/python3.8/site-packages/q2cli/util.py", line 229, in callback
    citations.save(fh)
  File "/Users/jgc/miniconda3/envs/dwq2/lib/python3.8/site-packages/qiime2/core/cite.py", line 54, in save
    entry = citation.fields.copy()
AttributeError: 'str' object has no attribute 'fields'
```

It would be nice to either allow the former (so you can just pass one citation if you only have one), or have a more informative error message in this case.

**Comment by ebolyen** [comment]
Hey @gregcaporaso,

Good idea, and I think we can even do better, let's just support an individual CitationRecord in Plugin, *register_function, register_view/format, and register_transformer.
