### ISSUE TITLE
default recycle-pools are incompatible with simultaneous execution of the same action

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#787]
I ran into this when running `qiime boots core-metrics` with a handful of different parameter settings. Two work-arounds are:

1) Specify the name of the recycle pool for each individual command, ensuring that the names of the recycle-pools are different (e.g., `--recycle-pool output-1` and `--recycle-pool output-2`). The catch here is the user is responsible for cleaning this up as QIIME 2 won't garbage collect user-named recycle pools.
2) Specify `--no-recycle` (in which case pipeline resumption won't be available).

**Comment by Oddant1** [comment]
Produces the following traceback

```
/home/anthony/miniconda3/envs/q2-amplicon-dev/lib/python3.9/site-packages/skbio/util/_warning.py:60: UserWarning: observed_otus is deprecated as of 0.6.0.
  warn(f"{func.__name__} is deprecated as of {ver}.")
/home/anthony/miniconda3/envs/q2-amplicon-dev/lib/python3.9/site-packages/skbio/stats/ordination/_principal_coordinate_analysis.py:146: RuntimeWarning: The result contains negative eigenvalues. Please compare their magnitude with the magnitude of some of the largest positive eigenvalues. If the negative ones are smaller, it's probably safe to ignore them, but if they are large in magnitude, the results won't be useful. See the Notes section for more details. The smallest eigenvalue is -0.013670709225275066 and the largest is 3.6056635405843824.
  warn(
Traceback (most recent call last):
  File "/home/anthony/src/qiime2/q2cli/q2cli/commands.py", line 526, in __call__
    results = self._execute_action(
  File "/home/anthony/src/qiime2/q2cli/q2cli/commands.py", line 598, in _execute_action
    results = action(**arguments)
  File "<decorator-gen-762>", line 2, in core_metrics
  File "/home/anthony/src/qiime2/qiime2/qiime2/sdk/action.py", line 342, in bound_callable
    outputs = self._callable_executor_(
  File "/home/anthony/src/qiime2/qiime2/qiime2/sdk/action.py", line 698, in _callable_executor_
    aliased_result = output._alias(prov)
  File "/home/anthony/src/qiime2/qiime2/qiime2/sdk/result.py", line 246, in _alias
    alias._archiver = archive.Archiver.from_data(
  File "/home/anthony/src/qiime2/qiime2/qiime2/core/archive/archiver.py", line 412, in from_data
    process_alias, data_path = cache._rename_to_data(uuid, path)
  File "/home/anthony/src/qiime2/qiime2/qiime2/core/cache.py", line 1169, in _rename_to_data
    process_alias = self._alias(uuid)
  File "/home/anthony/src/qiime2/qiime2/qiime2/core/cache.py", line 1197, in _alias
    self.named_pool._make_symlink(uuid, uuid)
  File "/home/anthony/src/qiime2/qiime2/qiime2/core/cache.py", line 1595, in _make_symlink
    os.symlink(src, dest)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/qiime2/anthony/data/18d0e3d5-e207-4ceb-922a-9f636ed40be9' -> '/tmp/qiime2/anthony/pools/recycle_diversity_core_metrics_b6574c7925e237c1d6cf4171584757414b8f08e3/18d0e3d5-e207-4ceb-922a-9f636ed40be9'
```

This happens because whichever process succeeds first nukes the process pool. The other processes attempt to create symlinks to the data in the recycle pool which no longer exists. If the recycle pool no longer exist, we'll just give up on creating that symlink and keep chugging along.
